language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
after_success:
- julia -e 'using Pkg; Pkg.add(["Coverage"])'
- julia -e 'using Pkg, Coverage, IncompleteLU; cd(joinpath(dirname(pathof(IncompleteLU)), "..")); Codecov.submit(process_folder())'